apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: cracker786/result007
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: postgres-config